server:
  port: 8081

# SPRING ----------------------------------------------------------------------------------------------------
spring:
  application:
    name: demo-service
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  # DATASOURCE ----------------------------------------------------------------------------------------------------
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: admin
    password: 123456
    driver-class-name: org.postgresql.Driver
  # JPA ----------------------------------------------------------------------------------------------------
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  messages:
    basename: messages
    use-code-as-default-message: true

cloud:
  aws:
    region:
      auto: false
      static: us-west-2
    stack:
      auto: false

logging:
  level:
    com:
      amazonaws:
        internal:
          InstanceMetadataServiceResourceFetcher: error
        util:
          EC2MetadataUtils: error

application:
  swagger:
    base-url: localhost:8081
  jwt:
    confirmation-secret: 123456
    time-to-live: 3600 # seconds

keycloak:
  realm: login-app
  auth-server-url: http://localhost:8080/auth
  ssl-required: external
  resource: login-app
  credentials:
    secret: 0b5c9662-94ea-4148-9c52-cde5034310a3
  use-resource-role-mappings: true
  bearer-only: true
