server:
  port: 8080

# SPRING ----------------------------------------------------------------------------------------------------
spring:
  application:
    name: demo-service
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  # DATASOURCE ----------------------------------------------------------------------------------------------------
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: admin
    password: 123456
    driver-class-name: org.postgresql.Driver
  # JPA ----------------------------------------------------------------------------------------------------
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  messages:
    basename: messages
    use-code-as-default-message: true

cloud:
  aws:
    region:
      auto: false
      static: us-west-2
    stack:
      auto: false

logging:
  level:
    com:
      amazonaws:
        internal:
          InstanceMetadataServiceResourceFetcher: error
        util:
          EC2MetadataUtils: error

application:
  swagger:
    base-url: localhost:8080/demo-service
  jwt:
    confirmation-secret: 123456
    time-to-live: 3600 # seconds
